import Link from 'next/link';
import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { BarChart3, CheckCircle2, CircleDollarSign, RefreshCw, TrendingUp, XCircle } from 'lucide-react';
import { auth } from '@/auth';
import { db } from '@/lib/db';
import { getRevenueOpsSettings, runRevenueOperationsAgent } from '@/lib/revenue-operations-agent';
import { logOperationsActivity } from '@/lib/operations-intelligence';
import { Badge } from '@/components/ui/badge'; import { Button } from '@/components/ui/button'; import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'; import { Input } from '@/components/ui/input'; import { Textarea } from '@/components/ui/textarea';
export const maxDuration = 300;
async function requireAdmin() { const session = await auth(); if (!session?.user) redirect('/sign-in'); const user = await db.user.findFirst({ where: { OR: [{ id: session.user.id }, ...(session.user.email ? [{ email: session.user.email }] : [])] }, select: { id: true, role: true } }); if (user?.role !== 'ADMIN') redirect('/role-selection'); return user; }
async function runNow() { 'use server'; await requireAdmin(); await runRevenueOperationsAgent({ trigger: 'MANUAL' }); revalidatePath('/admin/revenue'); }
async function saveSettings(formData: FormData) { 'use server'; await requireAdmin(); const num = (name: string, fallback: number, min: number, max: number) => Math.max(min, Math.min(max, Number(formData.get(name) || fallback))); const data = { enabled: formData.get('enabled') === 'true', projectedFeeRate: num('projectedFeeRate', 10, 0, 30), growthPackagePrice: num('growthPackagePrice', 499, 1, 10000), highValueJobThreshold: num('highValueJobThreshold', 2500, 100, 1000000), staleLeadHours: num('staleLeadHours', 48, 1, 720), stalledAwardDays: num('stalledAwardDays', 14, 1, 365) }; await db.revenueOpsSettings.upsert({ where: { id: 'default' }, update: data, create: { id: 'default', ...data } }); revalidatePath('/admin/revenue'); }
async function decide(formData: FormData) { 'use server'; const admin = await requireAdmin(); const id = String(formData.get('id') || ''), decision = String(formData.get('decision') || ''); if (!id || !['REVIEWING', 'APPROVED_PLAN', 'RESOLVED', 'DISMISSED'].includes(decision)) return; const now = new Date(), draftPlan = String(formData.get('draftPlan') || '').slice(0, 5000) || null; const item = await db.revenueOpportunity.update({ where: { id }, data: { status: decision, draftPlan, ...(decision === 'APPROVED_PLAN' ? { approvedById: admin.id, approvedAt: now } : {}), ...(decision === 'RESOLVED' ? { resolvedById: admin.id, resolvedAt: now } : {}), ...(decision === 'DISMISSED' ? { dismissedById: admin.id, dismissedAt: now } : {}) } }); await logOperationsActivity({ eventType: `REVENUE_OPPORTUNITY_${decision}`, actorType: 'ADMIN', actorId: admin.id, entityType: 'REVENUE_OPPORTUNITY', entityId: id, summary: `${item.title} marked ${decision.toLowerCase().replaceAll('_', ' ')}.`, details: { automatedBillingAction: false, estimatedValue: item.estimatedValue ? Number(item.estimatedValue) : null } }); revalidatePath('/admin/revenue'); }
const currency = (value: unknown) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(Number(value || 0));
const date = (value: Date | null) => value ? new Intl.DateTimeFormat('en-US', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'America/New_York' }).format(value) : 'Never';
const priorityClass = (value: string) => value === 'P1' ? 'bg-red-700 text-white' : value === 'P2' ? 'bg-amber-500 text-slate-950' : 'bg-blue-600 text-white';
export default async function RevenuePage() { await requireAdmin(); const [settings, opportunities, snapshots, runs, grouped] = await Promise.all([getRevenueOpsSettings(), db.revenueOpportunity.findMany({ orderBy: [{ status: 'asc' }, { priority: 'asc' }, { estimatedValue: 'desc' }], take: 250 }), db.revenueDailySnapshot.findMany({ orderBy: { snapshotDate: 'desc' }, take: 30 }), db.revenueOpsRun.findMany({ orderBy: { startedAt: 'desc' }, take: 15 }), db.revenueOpportunity.groupBy({ by: ['status'], _count: { _all: true } })]); const counts = Object.fromEntries(grouped.map((x) => [x.status, x._count._all])), active = opportunities.filter((x) => ['OPEN', 'REVIEWING'].includes(x.status)), closed = opportunities.filter((x) => !['OPEN', 'REVIEWING'].includes(x.status)).slice(0, 30), latest = snapshots[0]; return <main className="min-h-screen bg-muted/30"><div className="mx-auto max-w-7xl space-y-8 px-4 py-8 sm:px-6">
<header className="flex flex-wrap items-start justify-between gap-4"><div><Link href="/admin/operations" className="text-sm text-primary hover:underline">← Marketplace Operations</Link><div className="mt-3 flex items-center gap-3"><CircleDollarSign className="size-8 text-emerald-600" /><h1 className="text-3xl font-bold">Revenue & Monetization Operations</h1></div><p className="mt-2 max-w-4xl text-muted-foreground">Marketplace value and monetization intelligence. FixMyHome does not currently process project payments, so GMV and fee scenarios are estimates—not collected revenue.</p></div><form action={runNow}><Button className="gap-2"><RefreshCw className="size-4" />Run revenue scan</Button></form></header>
<section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-6 motion-safe:animate-in motion-safe:fade-in motion-safe:slide-in-from-bottom-2 motion-safe:duration-500"><Card className="border-violet-200 bg-violet-50/80 dark:border-violet-900 dark:bg-violet-950/35"><CardHeader><CardDescription>Agent</CardDescription><CardTitle>{settings.enabled ? 'Enabled' : 'Paused'}</CardTitle></CardHeader></Card><Card className="border-amber-200 bg-amber-50/80 dark:border-amber-900 dark:bg-amber-950/35"><CardHeader><CardDescription>Open opportunities</CardDescription><CardTitle>{counts.OPEN || 0}</CardTitle></CardHeader></Card><Card className="border-blue-200 bg-blue-50/80 dark:border-blue-900 dark:bg-blue-950/35"><CardHeader><CardDescription>Awarded value (30d)</CardDescription><CardTitle>{currency(latest?.awardedMarketplaceValue30d)}</CardTitle></CardHeader></Card><Card className="border-emerald-200 bg-emerald-50/80 dark:border-emerald-900 dark:bg-emerald-950/35"><CardHeader><CardDescription>Completed value (30d)</CardDescription><CardTitle>{currency(latest?.completedMarketplaceValue30d)}</CardTitle></CardHeader></Card><Card className="border-cyan-200 bg-cyan-50/80 dark:border-cyan-900 dark:bg-cyan-950/35"><CardHeader><CardDescription>Fee scenario ({settings.projectedFeeRate}%)</CardDescription><CardTitle>{currency(latest?.projectedFeeScenario30d)}</CardTitle></CardHeader></Card><Card className="border-teal-200 bg-teal-50/80 dark:border-teal-900 dark:bg-teal-950/35"><CardHeader><CardDescription>Growth pipeline</CardDescription><CardTitle>{currency(latest?.growthPackagePipelineValue)}</CardTitle></CardHeader></Card></section>
<Card><CardHeader><CardTitle>Forecast controls</CardTitle><CardDescription>These settings drive opportunity detection and scenarios only. They do not change pricing or charge anyone.</CardDescription></CardHeader><CardContent><form action={saveSettings} className="grid gap-4 md:grid-cols-3 lg:grid-cols-6"><label className="space-y-2 text-sm font-medium">Status<select name="enabled" defaultValue={String(settings.enabled)} className="h-10 w-full rounded-md border bg-background px-3"><option value="true">Enabled</option><option value="false">Paused</option></select></label><label className="space-y-2 text-sm font-medium">Fee scenario %<Input name="projectedFeeRate" type="number" step="0.1" defaultValue={settings.projectedFeeRate} /></label><label className="space-y-2 text-sm font-medium">Growth Package price<Input name="growthPackagePrice" type="number" defaultValue={Number(settings.growthPackagePrice)} /></label><label className="space-y-2 text-sm font-medium">High-value threshold<Input name="highValueJobThreshold" type="number" defaultValue={Number(settings.highValueJobThreshold)} /></label><label className="space-y-2 text-sm font-medium">Lead stale hours<Input name="staleLeadHours" type="number" defaultValue={settings.staleLeadHours} /></label><label className="space-y-2 text-sm font-medium">Award stalled days<Input name="stalledAwardDays" type="number" defaultValue={settings.stalledAwardDays} /></label><Button type="submit" variant="outline" className="w-fit md:col-span-3 lg:col-span-6">Save controls</Button></form></CardContent></Card>
<Card><CardHeader><CardTitle>Revenue opportunity queue</CardTitle><CardDescription>{active.length} opportunities require review. Approving a plan stores it only; it sends nothing and performs no billing action.</CardDescription></CardHeader><CardContent className="space-y-5">{active.map((item) => <article key={item.id} className="rounded-lg border p-5"><div className="flex flex-wrap justify-between gap-3"><div><div className="flex flex-wrap gap-2"><Badge className={priorityClass(item.priority)}>{item.priority}</Badge><Badge variant="outline">{item.type.replaceAll('_', ' ')}</Badge>{item.estimatedValue && <Badge variant="outline">{currency(item.estimatedValue)}</Badge>}</div><h2 className="mt-3 text-lg font-semibold">{item.title}</h2><p className="mt-1 text-sm text-muted-foreground">{item.summary}</p></div>{item.subjectType === 'JOB' && item.subjectId && <Button asChild size="sm" variant="outline"><Link href={`/jobs/${item.subjectId}`}>Open project</Link></Button>}</div><div className="mt-4 rounded-md bg-emerald-50 p-4 text-emerald-950 dark:bg-emerald-950/30 dark:text-emerald-100"><p className="text-sm font-semibold">Recommended action</p><p className="mt-1 text-sm">{item.recommendedAction}</p></div><details className="mt-3"><summary className="cursor-pointer text-xs text-muted-foreground">Evidence</summary><pre className="mt-2 overflow-x-auto rounded-md bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify(item.evidence, null, 2)}</pre></details><form action={decide} className="mt-4 space-y-3"><input type="hidden" name="id" value={item.id} />{item.draftPlan && <Textarea name="draftPlan" defaultValue={item.draftPlan} rows={3} />}<div className="flex flex-wrap gap-2"><Button name="decision" value="REVIEWING" variant="outline">Review</Button>{item.draftPlan && <Button name="decision" value="APPROVED_PLAN">Approve plan only</Button>}<Button name="decision" value="RESOLVED" variant="outline"><CheckCircle2 className="size-4" />Resolve</Button><Button name="decision" value="DISMISSED" variant="outline"><XCircle className="size-4" />Dismiss</Button></div></form></article>)}{!active.length && <p className="py-10 text-center text-sm text-muted-foreground">Run the agent to create the first opportunity queue.</p>}</CardContent></Card>
<section className="grid gap-8 xl:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><BarChart3 className="size-5" />Latest snapshot</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p>Growth Package leads: <strong>{latest?.growthPackageLeads30d || 0}</strong></p><p>Attribution coverage: <strong>{latest?.attributionCoverage30d || 0}%</strong></p><p className="text-muted-foreground">Payment revenue tracked: <strong>No</strong> · Fee scenario is forecast-only.</p></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><TrendingUp className="size-5" />Run history</CardTitle><CardDescription>Last run: {date(settings.lastRunAt)}</CardDescription></CardHeader><CardContent className="space-y-3">{runs.map((run) => <div key={run.id} className="rounded-md border p-3 text-sm"><div className="flex justify-between"><span>{run.trigger} · {run.status}</span><span>{date(run.startedAt)}</span></div><p className="text-muted-foreground">{run.recordsScanned} records · {run.opportunitiesDetected} opportunities</p></div>)}</CardContent></Card></section>
{closed.length > 0 && <Card><CardHeader><CardTitle>Recently decided</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">{closed.map((item) => <div key={item.id} className="rounded-md border p-3 text-sm"><div className="flex justify-between gap-2"><span className="font-medium">{item.title}</span><Badge variant="outline">{item.status.replaceAll('_', ' ')}</Badge></div></div>)}</CardContent></Card>}
</div></main>; }